# .github/workflows/add-header-pr.yml
name: add-header-pr

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - ${{ github.event.repository.default_branch }}
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  guard:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
    steps:
      - name: Verificar mergeabilidade e checks
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) core.setFailed('Sem PR no contexto.');
            if (pr.state !== 'open') core.setFailed('PR fechado.');
            if (pr.mergeable === false) core.setFailed('PR não mergeável.');
            if (pr.mergeable_state && pr.mergeable_state !== 'clean') {
              core.setFailed(`PR não limpo para merge (mergeable_state=${pr.mergeable_state}).`);
            }

  run:
    runs-on: ubuntu-latest
    needs: guard
    if: ${{ success() }}
    steps:
      - name: Checkout (histórico completo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependências
        run: |
          npm ci || npm i

      - name: Aplicar cabeçalhos nos arquivos do PR
        env:
          OPENROUTER_TOKEN: ${{ secrets.KEY_AGENT_RELATIVE_PATH }}
          USE_OPENROUTER: ${{ vars.USE_OPENROUTER || 'false' }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          npx ts-node tools/openrouter/add-headers-pr.ts

      - name: Push na branch do PR (se houve mudanças)
        run: |
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore(headers): inserir cabeçalhos relativos nos arquivos do PR"
            git push origin "HEAD:${{ github.event.pull_request.head.ref }}"
          else
            echo "Sem mudanças."
          fi
