# .github/workflows/test-pr.yml
name: test-pr

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    if: ${{ github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.repo.full_name == github.repository }}
    name: Detectar alterações
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.filter.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verificar arquivos novos ou modificados
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            any:
              - added: '**'
              - modified: '**'

  test:
    name: Executar testes
    needs: changes
    if: ${{ needs.changes.result == 'success' && needs.changes.outputs.any_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependências
        run: |
          npm ci || npm i

      - name: Executar testes
        run: npm test
